Resources:
  UserData:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: userDetail
      AttributeDefinitions:
        - AttributeName: userEmail
          AttributeType: S
      KeySchema:
        - AttributeName: userEmail
          KeyType: HASH
      # Set the capacity based on the stage
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2